name: Add Reviewers

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      if: |
        github.event_name == 'push' ||
        !startsWith(github.event.pull_request.head.label, 'tuya:')
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: ShinyLeee,youngjuning
        re-request-when-approved: true
        re-request-when-changes-requested: true
