# Triggered when code is pushed to any branch in a repository
name: Sync TYNativeApi
on:
  push:
    branches:
      - TYNativeApi
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "ShinyLeee,youngjuning"
        pr_assignee: "ShinyLeee,youngjuning"
        pr_allow_empty: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
